after_script:
  - docker images

before_script:
  - cd "$VERSION"
  - IMAGE="dash-core:${VERSION/\//-}"

env:
  - VERSION=0.12
  - VERSION=0.12/alpine

language: bash

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD >/dev/null 2>&1
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Dash Core"

services: docker
